osx_image: xcode11
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=tapestry
script:
- set -o pipefail && swift test --generate-linuxmain -Xswiftc -target -Xswiftc x86_64-apple-macosx10.12 
before_deploy:
- swift build --static-swift-stdlib --configuration release
- export BINARY_PATH=`swift build --show-bin-path --configuration release`/FRAMEWORK_NAME
- mv "$BINARY_PATH" .
- zip -r $FRAMEWORK_NAME-$TRAVIS_TAG.zip LICENSE $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: wFWClyyBgwbOvMDX1naWN3HSW5Lh3AtBlTjgDGvWmVLPahHSucppFXVE18vGs6A0eNdoCrDz9Cc1gFXDkZe6z6NxYoB7dupJCsiPAiMDrGdbgqgWAGRCgMncWPT3DjkbiNQBfK5TXUF4/DVmSyKvej/V70fa0oMuzvy4V+TiqKD2aC2sNXmPu582NDFiSJ9pIOpWmShPfZ/b/FGXJ5FPZ4i4tIZdF+1Z8lhSdU//K0CQAkVtTmuQaj4mWR1mbyZJQFOlCGWCtn5AyLEpvjrheuRH4DhSJKsIo5hOT8J/820AzFofKb0NrIErYOb+0iO52/K93hhg6jTI2SyPYgrPLyYPJFvhORwZPx56a6WMrayHQ+sVdMruiSdpo5ecNce/tiLncImTngSl4R6MTNLewRkTaaVnXtkLRH50O5BZmMghU7zuSiGgODG4JCIbVEUuH4SjqUS7GG7UlJmIKLF3z0oAH2rpQaqEX2Y0GLQXgIYOyv7vQvhMLUoIo5exrr62BQuEcvB3PgNh3sxk52APUaceRxb7VjqzEBDqGD0+ZQxXRsn0JjES7DA2D7OosBYtexoFX7et1pTrDT2FIDqVvq7oJ3P5LAbfSMIR1mxefHr0+46etoKGQrvwvGwzShFUhIBH9VzktoHOhos+RkbPGAXmM7JLIOyP26S577TBqJA=
  file: "$FRAMEWORK_NAME-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/tapestry
    tags: true
