#if !canImport(ObjectiveC)
import XCTest

extension GitControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GitControllerTests = [
        ("test_init_git_fails", test_init_git_fails),
        ("test_init_git_succeeds", test_init_git_succeeds),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GitControllerTests.__allTests__GitControllerTests),
    ]
}
#endif
