#if !canImport(ObjectiveC)
import XCTest

extension TapestryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TapestryTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TapestryTests.__allTests__TapestryTests),
    ]
}
#endif
