#if !canImport(ObjectiveC)
import XCTest

extension PackageControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageControllerTests = [
        ("test_initPackage_when_library", test_initPackage_when_library),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PackageControllerTests.__allTests__PackageControllerTests),
    ]
}
#endif
