#if !canImport(ObjectiveC)
import XCTest

extension ExampleGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExampleGeneratorTests = [
        ("test_example_sources_are_generated", test_example_sources_are_generated),
        ("test_folder_for_example_is_created", test_folder_for_example_is_created),
        ("test_generator_generates_project", test_generator_generates_project),
    ]
}

extension ExampleModelLoaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExampleModelLoaderTests = [
        ("test_loadProject", test_loadProject),
    ]
}

extension PackageControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageControllerTests = [
        ("test_initPackage_throws_when_wrong_input", test_initPackage_throws_when_wrong_input),
        ("test_initPackage_when_executable", test_initPackage_when_executable),
        ("test_initPackage_when_library", test_initPackage_when_library),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExampleGeneratorTests.__allTests__ExampleGeneratorTests),
        testCase(ExampleModelLoaderTests.__allTests__ExampleModelLoaderTests),
        testCase(PackageControllerTests.__allTests__PackageControllerTests),
    ]
}
#endif
